### PR TITLE
Log rotate patch

### PR DESCRIPTION
**Pull request by osv**
- Add install hook, that create sudoers cfg for running "lib/dokku-cfg-logrotate" command which update /etc/logrotate.d/dokku-app.d/$APP rotate cfg (logrotate require these cfg be as root owner and 644).
- Update Readme for installing and logrotate
- Fix progrium/buildstep, supervisor command now /exec_svd, which is copy of /exec generated by "builder".
- Some indent of echo

### CODE REVIEW

**Comment by michaelshobbs** [comment]
Arguably, log rotation is out of scope for this plugin. In fact I handle log rotation elsewhere in my infrastructure and this would definitely collide there.

**Comment by osv** [comment]
Yes, that out of scope.
So don't want make another-not-maintainable fork :)
 Logrotate maybe disabled by default.

**Comment by michaelshobbs** [comment]
Shall we close this PR then?

**Comment by osv** [comment]
Sure

**Pull request closed without merging**
